# frozen_string_literal: true

require "json"

# Not a spec for a class: this is #109's rule that the error reference page
# cannot silently miss a subclass the way a hand-maintained list would.
#
# The page renders `site/src/data/errors.json`, which is generated by walking
# the object space for every class that mixes in `ActiveSanction::Error` --
# see site/bin/generate_errors.rb for why that finds a class the mdx's own
# `editorial` map has no entry for even when nobody remembered to update
# either one by hand.
RSpec.describe "the generated error data behind the error reference page" do
  let(:root) { File.expand_path("..", __dir__) }

  let(:committed) { File.read(File.join(root, "site", "src", "data", "errors.json")) }

  let(:generated) do
    load File.join(root, "site", "bin", "generate_errors.rb")
    GenerateErrors.call
  end

  let(:errors) { JSON.parse(committed).fetch("errors") }

  let(:page) { File.read(File.join(root, "site", "src", "content", "docs", "reference", "errors.mdx")) }

  it "is committed" do
    expect(File).to exist(File.join(root, "site", "src", "data", "errors.json"))
  end

  # The whole point. If this fails, run `bundle exec rake site:errors` and
  # read the diff: it is a new subclass, a renamed one, or an attribute added
  # to an existing one, and all three are worth seeing.
  it "matches what the generator produces today" do
    expect(committed).to eq(generated),
                         "site/src/data/errors.json is stale. Run `bundle exec rake site:errors`."
  end

  it "carries every class in ActiveSanction::Error's hierarchy, and none outside it" do
    live = ObjectSpace.each_object(Class)
                      .select { |klass| klass < Exception && klass.ancestors.include?(ActiveSanction::Error) }
                      .map { |klass| klass.name.delete_prefix("ActiveSanction::") }

    expect(errors.map { |error| error["name"] }).to match_array(live)
  end

  # The reference page's whole reason to exist: every generated class must be
  # named on the page, or the page is exactly the stale hand-typed list #109
  # exists to replace.
  it "names every generated error class on the reference page" do
    missing = errors.reject { |error| page.include?(error["name"]) }

    expect(missing.map { |error| error["name"] }).to be_empty
  end

  it "names the four bundle failures the page is required to distinguish" do
    bundle_failures = errors.map { |error| error["name"] }.grep(/\ASnapshot::Bundle::/)

    expect(bundle_failures).to match_array(
      %w[Snapshot::Bundle::Corrupt Snapshot::Bundle::Unsigned
         Snapshot::Bundle::UnsupportedFormat Snapshot::Bundle::UntrustedSignature]
    )
  end
end
